import { useState } from 'react'
import Brand from '../components/Brand'
import Button from '../components/Button'
import { Icon } from '../components/Icons'
import StatCard from '../components/StatCard'

const navItems = [['home','Overview'],['map','Live network'],['activity','Analytics'],['layers','Assets']]
const poles = [{top:'38%',left:'38%',state:'active'},{top:'55%',left:'56%',state:'idle'},{top:'26%',left:'67%',state:'active'},{top:'67%',left:'80%',state:'fault'},{top:'49%',left:'83%',state:'active'},{top:'27%',left:'18%',state:'idle'},{top:'72%',left:'27%',state:'active'}]
const activity = [
  { tag:'ACTIVE', text:'Sector 12 / P-2473 pre-brightened', time:'Now', tone:'green' },
  { tag:'SAVING', text:'Zone C adaptive load adjusted', time:'4m ago', tone:'blue' },
  { tag:'ATTENTION', text:'P-2419 driver anomaly detected', time:'12m ago', tone:'amber' },
]

export default function DashboardPage({ navigate }) {
 const [selected, setSelected] = useState('Overview')
 const [range, setRange] = useState('Today')
 return <main className="dashboard-page">
  <aside className="dash-sidebar"><button onClick={() => navigate('home')}><Brand light compact /></button><div className="side-district"><span className="district-dot"/><div><small>ACTIVE DISTRICT</small><b>New Delhi Central</b></div><Icon name="chevron" size={15}/></div><nav>{navItems.map(([icon,label]) => <button className={selected===label?'selected':''} onClick={() => setSelected(label)} key={label}><Icon name={icon} size={19}/><span>{label}</span></button>)}</nav><div className="side-bottom"><button><Icon name="shield" size={18}/><span>System integrity</span><i className="online-indicator"/></button><button onClick={() => navigate('home')}><Icon name="logout" size={18}/><span>Sign out</span></button></div></aside>
  <div className="dash-main"><header className="dash-header"><div><p className="eyebrow">NATIONAL STREETLIGHT COMMAND</p><h1>{selected}</h1></div><div className="dash-actions"><button className="icon-button"><Icon name="bell" size={19}/><i/></button><button className="profile"><span>ES</span><div><b>Ekta Singh</b><small>Operations Officer</small></div><Icon name="chevron" size={14}/></button></div></header>
   <section className="dash-content"><div className="dashboard-greeting"><div><h2>Good evening, Ekta <span>✦</span></h2><p>Your network is performing beautifully tonight.</p></div><div className="date-control"><Icon name="sun" size={17}/><button onClick={() => setRange(range==='Today'?'This week':'Today')}>{range}<Icon name="chevron" size={14}/></button></div></div>
   <div className="stats-grid"><StatCard icon="bolt" label="Energy saved today" value="1,284 kWh" change="↑ 18.2% vs. baseline"/><StatCard icon="sun" label="Network luminosity" value="64.8%" change="Optimised across 412 poles" tone="blue"/><StatCard icon="activity" label="Active assets" value="408 / 412" change="4 assets need attention" tone="amber"/><StatCard icon="shield" label="Safety floor maintained" value="100%" change="All zones within policy"/></div>
   <div className="dash-grid"><section className="map-card panel"><div className="panel-title"><div><p className="eyebrow">REAL-TIME COVERAGE</p><h3>Central district network</h3></div><button className="soft-button"><Icon name="filter" size={15}/> All assets</button></div><div className="map-visual"><div className="map-river"/><div className="map-road r1"/><div className="map-road r2"/><div className="map-road r3"/><div className="map-road r4"/><div className="map-block b1"/><div className="map-block b2"/><div className="map-block b3"/>{poles.map((p,i)=><button title={`Pole ${2430+i}`} className={`map-pole ${p.state}`} style={{top:p.top,left:p.left}} key={i}><span/><i/></button>)}<div className="map-legend"><span><i className="legend-green"/> Active</span><span><i className="legend-grey"/> Baseline</span><span><i className="legend-amber"/> Attention</span></div><div className="map-controls"><button>+</button><button>−</button></div></div><div className="map-footer"><span><i className="pulse-dot"/> Live device telemetry</span><span>412 assets monitored <Icon name="arrow" size={15}/></span></div></section>
   <section className="activity-card panel"><div className="panel-title"><div><p className="eyebrow">MOMENTS AGO</p><h3>Network activity</h3></div><button className="more-button">•••</button></div><div className="activity-list">{activity.map(item=><div className="activity-item" key={item.text}><span className={`activity-pin ${item.tone}`}/><div><small className={item.tone}>{item.tag}</small><p>{item.text}</p><time>{item.time}</time></div></div>)}</div><button className="activity-link">View all activity <Icon name="arrow" size={16}/></button><div className="integrity-card"><div><span className="integrity-mark"><Icon name="shield" size={20}/></span><div><small>SYSTEM INTEGRITY</small><b>All systems normal</b></div></div><span className="integrity-score">99.9%</span></div></section></div>
   <section className="chart-card panel"><div className="panel-title"><div><p className="eyebrow">VERIFIED PERFORMANCE</p><h3>Energy performance</h3></div><div className="chart-key"><span><i/> Adaptive consumption</span><span><i/> Baseline estimate</span><Button variant="quiet" icon="download">Report</Button></div></div><div className="chart-wrap"><svg viewBox="0 0 920 220" preserveAspectRatio="none"><defs><linearGradient id="chartFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#9ad67d" stopOpacity=".34"/><stop offset="100%" stopColor="#9ad67d" stopOpacity="0"/></linearGradient></defs><g className="chart-lines"><path d="M0 20H920M0 75H920M0 130H920M0 185H920"/></g><path className="baseline-line" d="M0 150 C60 132, 85 158, 140 122 S230 141, 286 102 S365 128, 425 72 S515 116, 570 66 S650 98, 720 43 S820 78,920 25"/><path className="energy-fill" d="M0 168 C60 158,85 177,140 151 S230 165,286 138 S365 151,425 110 S515 140,570 105 S650 133,720 92 S820 113,920 76 L920 220 L0 220Z"/><path className="energy-line" d="M0 168 C60 158,85 177,140 151 S230 165,286 138 S365 151,425 110 S515 140,570 105 S650 133,720 92 S820 113,920 76"/><circle cx="720" cy="92" r="5" className="chart-point"/></svg><div className="chart-labels"><span>18:00</span><span>20:00</span><span>22:00</span><span>00:00</span><span>02:00</span><span>Now</span></div></div></section>
   </section></div>
 </main>
}
